[build]
  command = "npm run build" 
  publish = "public"

[dev]
  command = "npm start" 

[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200 

[[headers]] 
  for = "/*" 
  [headers.values]
    X-Frame-Options = "DENY" 

[build.environment]
  NODE_VERSION = "14" 